language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - flake8 grinpy
  - pydocstyle grinpy
  - coverage run python setup.py test
after_success:
  - codecov
deploy:
  provider: pypi
  user: somacdivad
  password:
    secure: H7PzVxwJuqymlbb6CE98najeeYVoG9QyUZAytiOy1hbvUSERiwmmqkVKlhUYeNZiQTyQb2ajvIqxwblkZxt54gS0Tg0dTHfMOjjkfsc/9YCWsn8vRhLRLFtBeOLWZFQK3bK9EZPWkaJE001m4Ppe1u4emenERDvRL21U9tTbhMycjCVVPAa3DuGf0GXiMvKOat2HB5jTrjBqbGY8ggxezB5MrJLzNemVDGp2tIiwX64Gtm1Mqpr/CpL55YqrCpyxglUg7c2I1iWSP3+sbdHxwDzGyM/lWfRi+pJ0LQTDj4QAssQeelAlQwiZfdZWmzFlVvyeOcGJ9gmrOYo54Js65yevj0EFa0KGc5plf33nZIEm2je42dCGAp01sLoQn1avz9lcJTyg83+3ql/csxuxuUxkTMhLm4dHu7B7ua1UcZQQ2/LjlYTare2xmTBWsh+0mCXTVrZeNpHoGxBlRyC1O+AfPfkQmqtD7CuoA7AkuUQWNen4rjWBkjhPoxdk/BKkdy5E9IsgM78rrISdGe+RHHB1tl472TMQZ49vYMZx9KrDFt+sDbJVq08h27GpR8u8tzQzQI+5TdlBbTDGaxDtsx12cfLopNCQEveLYSRLxs3iyiDj06aeMnmCU8eMJo/jFtyGXeiCSv9Y+pIT3Crirm2HikKtkmX/8C6pGoCVpZA=
  on:
    tags: true
