# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "docs/requirements_dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements_dev.txt -r docs/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "docs/requirements_dev.txt" }}

      - run:
          name: lint code
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: check code format
          command: |
            . venv/bin/activate
            make check-formatting

      - run:
          name: lint docs
          command: |
            . venv/bin/activate
            doc8 docs/
  build:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "docs/requirements_dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements_dev.txt -r docs/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "docs/requirements_dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run:
          name: upload coverage report
          command: |
            . venv/bin/activate
            codecov -t=$CODECOV_TOKEN

      - run:
          name: build html docs
          command: |
            . venv/bin/activate
            cd docs
            make html

      - store_artifacts:
          path: docs/_build
          destination: docs

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build:
          requires:
            - lint
