# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements_dev.txt -r docs/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: check code format
          command: |
            . venv/bin/activate
            make check-formatting

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run:
          name: upload coverage report
          command: |
            . venv/bin/activate
            codecov -t=$CODECOV_TOKEN

  docs:
    docker:
      - image: circleci/python:3
      - image: danteev/texlive

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - doc-dependencies-{{ checksum "docs/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - doc-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r docs/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: doc-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: lint docs
          command: |
            . venv/bin/activate
            doc8 docs/

      - run:
          name: build docs
          command: |
            . venv/bin/activate
            cd docs/
            make latexpdf

      - store_artifacts:
          path: _build/latex/GrinPy.pdf
          destination: docs/GrinPy_Docs.pdf

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs:
          requires:
            - build

